steps:
  - id: api - yarn install
    name: node:12
    entrypoint: yarn
    args: ["install", "--frozen-lockfile"]
    dir: api

  - id: api - generate .env file
    name: node:12
    entrypoint: yarn
    args: ["create-env"]
    dir: api

  - id: api - build
    name: node:12
    entrypoint: yarn
    args: ["build"]
    dir: api
