steps:
  - id: api - yarn install
    name: node:12
    entrypoint: yarn
    args: ["install", "--frozen-lockfile"]
    dir: api

  - id: api - generate .env file
    name: node:12
    entrypoint: yarn
    args: ["create-env"]
    dir: api

  - id: api - build
    name: node:12
    entrypoint: yarn
    args: ["build"]
    dir: api

  - id: copy the app.yaml
    name: bash
    args: ["-c", "cp infra/app-engine.yaml api/app-engine.yaml"]

  - id: deploy
    name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy", "app-engine.yaml", "--version", "production"]
    dir: api
